### ISSUE TITLE
awesome if you could blog the internals of this

### ISSUE THREAD

**Issue by born2net** [Hacklone/angular2-cool-infinite-grid#1]
Would be awesome if you could do a blog on the internal workings and how you implemented this component in details

great work

Sean

**Comment by Hacklone** [comment]
Thanks, good idea. 👍 
Will write it in some days :)

**Comment by born2net** [comment]
sweeeet!
will add it to my Kitchen sink!
Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by Hacklone** [comment]
So here's an article I wrote on infinite scrolling :)

https://medium.com/@Hacklone/how-virtual-infinite-scrolling-works-239f7ee5aa58
