### ISSUE TITLE
Update  this.myItemIterator out of Constructor

### ISSUE THREAD

**Issue by AbelValdez** [Hacklone/angular2-cool-infinite-grid#3]
Hello I want to implement the Cool Grid  plugin I think it is awesome, but I have the following issue
When I try to initialize this code out of the constructor for example ngOnInit

this.myItemIterator = {
            next: function(fromIndex: number, length: number) {
...

I get the following error:
TypeError: Cannot read property 'next' of undefined
    at CoolInfiniteGridComponent.eval (infinite-grid.component.js:135)
I need to init there because I'm trying to get my Item Array from Rest full API.

Could you Help me please

**Comment by Hacklone** [comment]
Hey,

Did you bind the itemIterator into your component? 
```<cool-infinite-grid [itemIterator]="myItemIterator"```

**Comment by Hacklone** [comment]
I updated the package to throw an error if any of the mandatory parameters are not supplied :)

**Comment by AbelValdez** [comment]
Hello Hacklone, yes I already bind it even as same as you example. My problem here  is my item Array is empty before I init myItemIterator. 

Then when I want to update the array Item inside of myItemIterator how can I do it. I did it like this code but it doesnt shows any changes.

Code:


`
```
     items = []; 

     constructor (_itemPosterService: ItemPosterService,) {
        this._itemPosterService = _itemPosterService; 
     }

    public async ngOnInit() {
        const self = this;
        await this.loadArray();        
        this.myItemIterator = {
            next: function(fromIndex: number, length: number) {
                let value = self.items.slice(fromIndex, fromIndex + length);
                if (!value.length) {
                    value = null;
                }
                return {
                    value: Promise.resolve(value),
                    done: false
                };
            }
        };
     }
     
     async loadArray() {
         await this._itemPosterService.getItemsPostersArray("movies").subscribe(
             res => {
                 this.items = res
             }
         );
     }

```
`

**Comment by Hacklone** [comment]
Oh i get it now :)

The problem is that in ```asnyc ngOnInit() {``` you load the array asynchronously before setting the myItemIterator property, so angular will bind undefined instead of the itemIterator.

I would change the code to this:
```typescript
public ngOnInit() {
    const self = this;
    //-----> remove this await this.loadArray(); 
       
    this.myItemIterator = {
        next: (fromIndex: number, length: number) => {
            return {
                value: this._getItems(fromIndex, length)
            };
        }
    };
}

private async _getItems(fromIndex: number, length: number) {
    if (!self.items) {
        await this.loadArray();
    }

    let value = self.items.slice(fromIndex, fromIndex + length);
    if (!value.length) {
        value = null;
    }

    return value;
}
```

Did this help?

**Comment by AbelValdez** [comment]
No I haven't had luck :(

I got other console error:

> Angular is running in the development mode. Call enableProdMode() to enable the production mode.
> infinite-grid.component.js:150 TypeError: Cannot read property 'slice' of undefined
>     at ListRecyclerComponent.eval (ListRecycler.component.ts:68)
>     at step (ListRecycler.component.js:41)
>     at Object.eval [as next] (ListRecycler.component.js:22)
>     at fulfilled (ListRecycler.component.js:13)
>     at ZoneDelegate.invoke (zone.js?1495640494183:365)
>     at Object.onInvoke (ng_zone.ts:261)
>     at ZoneDelegate.invoke (zone.js?1495640494183:364)
>     at Zone.run (zone.js?1495640494183:125)
>     at zone.js?1495640494183:758
>     at ZoneDelegate.invokeTask (zone.js?1495640494183:398)
>     at Object.onInvokeTask (ng_zone.ts:253)
>     at ZoneDelegate.invokeTask (zone.js?1495640494183:397)
>     at Zone.runTask (zone.js?1495640494183:165)
>     at drainMicroTaskQueue (zone.js?1495640494183:591)
>     at XMLHttpRequest.ZoneTask.invoke (zone.js?1495640494183:464)
> ListRecycler.component.ts:81 Items Array: 3399

```
<cool-infinite-grid [itemIterator]="myItemIterator" [itemHeight]="150" [itemWidth]="100" [itemSpace]="5">               
             <ng-template let-item>
                <item-poster [url]="item.HDPosterUrl" [title]="item.TitleLat">
                </item-poster>     
             </ng-template>          
        </cool-infinite-grid>
```

```


export class ListRecyclerComponent implements OnInit { 
     _itemPosterService: ItemPosterService;
     str_search: string;
     @Input() category: string;

     myItemIterator: object;
     items: Array<any>; 

     constructor (_itemPosterService: ItemPosterService,) {
        this._itemPosterService = _itemPosterService;        
     }
  
     public  ngOnInit() {        
        const self = this;    
        this.myItemIterator = {
            next: function(fromIndex: number, length: number) {
               return {
                value: self._getItems(fromIndex, length)
                };
            }
        };
     }

    private  async _getItems(fromIndex: number, length: number) {
        const self = this; 

        if (!this.items) {
            await this.loadArray();
        }

        let value = self.items.slice(fromIndex, fromIndex + length);
        if (!value.length) {
            value = null;
        }

        return value;
    }


    private async loadArray() {
         await this._itemPosterService.getItemsPostersArray("movies").subscribe(
             res => {
                 this.items = res
                 console.log("Items Array: "+ this.items.length);

             }
         );
     }
```

**Comment by Hacklone** [comment]
Yeah the loadArray needs fixing too:

```typescript
private async loadArray() {
     this.items = await this._itemPosterService.getItemsPostersArray("movies").toPromise();
}
```

Hope now it will work :)

**Comment by AbelValdez** [comment]
Ready It works.
Thanks a lot.

```
  private  async _getItems(fromIndex: number, length: number) {
        const self = this; 
        let promise;
        if (!self.items) {
            promise = await this.loadArray().then(res => {
                this.items = res.json();
            });
        }       

        let value = self.items.slice(fromIndex, fromIndex + length);
        if (!value.length) {
            value = null;
        }

        return value;
    }


    private async loadArray() {
         return await this._itemPosterService.getItemsPosters("movies").toPromise();
     }
```

The solution was that I was using Async/await function in an Observable subscribe  and  Async/await just works with Promises

> Another thing to be aware of is that async/await only works with Promises, not with RxJS Observables.
>https://labs.encoded.io/2016/12/08/asyncawait-with-angular/

**Comment by AbelValdez** [comment]
Ok I fix The error messages and it works with my server, but the main question is
If the variable  `this.myItemIterator` is already defined and I want to change the item array inside how can I do it. 
How can I update the binding variable `this.myItemIterator.
`

**Comment by Hacklone** [comment]
Simply change the items in the this.items array and refresh the grid:

```typescript
@ViewChild(CoolInfiniteGridComponent)
public gridComponent;

public async changeItemsInArrayAsync() {
    await this.loadArray();

    await this.gridComponent.reRenderAsync();
}
```

**Comment by AbelValdez** [comment]
Thanks for your help @Hacklone that's a great Component plugin

Here the solution:
HTLM:
` <cool-infinite-grid #gridElement [itemIterator]="myItemIterator" [itemHeight]="150" [itemWidth]="150" [itemSpace]="5">   `   

Code:
```
  @ViewChild('gridElement')
    public gridComponent: CoolInfiniteGridComponent;

    private async changeItemsInArrayAsync() {        
        await this.gridComponent.reRenderAsync();
    }
```
Usage:
```

private async searchInArray(word: string) {
         searchArray [ ] ...... //obtain the new item array and replace the current items array.
        this.items = searchArray;
        if(this.items && this.items.length > 0 )
            await this.changeItemsInArrayAsync();

 }
```
